const teams = [
    "ACI Motorsports",
    "AF Corse",
    "AOA Racing",
    "Archangel Motorsports",
    "Ascent Racing",
    "Auto Technic Racing",
    "BGB Motorsports",
    "Bennett Motorsports",
    "BimmerWorld",
    "Black Swan Racing",
    "Blackdog Speed Shop",
    "BSI Racing",
    "Carrus Callas Raceteam",
    "CDR Valkyrie",
    "Chouest Povoledo Racing",
    "Chicago Performance & Tuning, Co.",
    "Conquest Racing",
    "Copeland Motorsports",
    "CRP Racing",
    "Crowdstrike by Riley",
    "DRS",
    "DXDT Racing",
    "Eagles Canyon Racing",
    "Esses Racing with Mercedes-Benz of Austin",
    "Extreme Velocity Motorsports",
    "Fast Track Racing",
    "Flying Lizard Motorsports",
    "FTG Racing",
    "GMG Racing",
    "Godwin Motorsports",
    "HART Alabama",
    "Hanley Motorsports",
    "Heart of Racing Team",
    "Ian Lacy Racing",
    "JMF Motorsports",
    "Kaplan Racing Systems",
    "KRUGSPEED",
    "LA Honda World Racing",
    "Lone Star Racing",
    "Lucas Racing",
    "Mashore Autobody",
    "MDK Motorsports",
    "McCumbee McAleer Racing",
    "MISHUMOTORS",
    "MINI JCW Team",
    "MMG",
    "NOLASPORT",
    "Nitro Motorsports",
    "OpenRoad Racing",
    "OGH Motorsports",
    "P1 Groupe",
    "Precision Racing LA",
    "Precision Racing LA with PT Autosport",
    "ProSport Competition",
    "RVA Graphics Motorsports by Speed Syndicate",
    "RS1",
    "Racers Edge Motorsports",
    "RealTime Racing",
    "RENNtech Motorsports",
    "Ricca Autosport",
    "Rigid Speed Company",
    "Rockwell Autosport Development",
    "Rooster Hall Racing",
    "SKI Autosports",
    "ST Racing",
    "Smooge Racing",
    "TKO Motorsports",
    "TR3 Racing",
    "TRG - The Racers Group",
    "TechSport Racing",
    "Tentador Tequila Racing",
    "Tommy McCarthy Racing",
    "Triarsi Competizione",
    "Turner Motorsport",
    "Valkyrie Velocity",
    "VGRT",
    "Zotz Racing",
    "Zotz Racing/ CCDP Racing",
];

export { teams };
